"""Adoção do Alembic (baseline + stamp) e guarda de drift.

initialize_database() agora: garante o schema (``_run_schema_init``, idempotente)
e concilia o ponteiro Alembic — fresh→stamp head, legado→stamp baseline, já
versionado→upgrade head. E ``test_autogenerate_is_clean`` é a GUARDA: se um
model mudar sem uma revision, ``alembic check`` falha no CI.
"""

from __future__ import annotations

import os
import tempfile

os.environ.setdefault("APP_MASTER_KEY", "test-master-key-for-centralops-suite-12345")
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("SESSION_SECURE_COOKIE", "false")

import pytest
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import sessionmaker

from backend.app.db import database
import backend.app.db.models  # noqa: F401  (popula o metadata)


@pytest.fixture()
def temp_db(monkeypatch):
    path = tempfile.NamedTemporaryFile(suffix=".db", delete=False).name
    eng = create_engine(
        f"sqlite:///{path}", connect_args={"check_same_thread": False}
    )
    monkeypatch.setattr(database, "engine", eng)
    monkeypatch.setattr(database, "SessionLocal", sessionmaker(bind=eng))
    monkeypatch.setattr(database, "DATABASE_URL", f"sqlite:///{path}")
    yield eng
    eng.dispose()


def _alembic_version(eng):
    with eng.connect() as conn:
        if not inspect(conn).has_table("alembic_version"):
            return None
        return conn.execute(text("SELECT version_num FROM alembic_version")).scalar()


def test_fresh_db_creates_schema_and_stamps_head(temp_db):
    database.initialize_database()
    assert inspect(temp_db).has_table("app_users")
    assert inspect(temp_db).has_table("destinations")
    assert _alembic_version(temp_db) == database._BASELINE_REVISION


def test_legacy_db_is_adopted_via_stamp(temp_db):
    # Simula um DB legado pré-Alembic: schema presente, SEM alembic_version.
    database._run_schema_init()
    assert inspect(temp_db).has_table("app_users")
    assert _alembic_version(temp_db) is None

    database.initialize_database()  # deve ADOTAR sem erro (não re-cria nada).
    assert _alembic_version(temp_db) == database._BASELINE_REVISION


def test_init_is_idempotent(temp_db):
    database.initialize_database()
    database.initialize_database()  # 2ª vez não levanta nem duplica.
    assert _alembic_version(temp_db) == database._BASELINE_REVISION


def test_autogenerate_is_clean(temp_db):
    """GUARDA: ``Base.metadata`` (models) == schema do baseline. Se um model
    mudou sem uma revision Alembic, ``command.check`` levanta com o diff."""
    from alembic import command

    database.initialize_database()
    cfg = database._alembic_config()
    # Não levanta AutogenerateDiffsDetected ⇒ sem operações pendentes.
    command.check(cfg)
